# ==============================================================================
# 【設定ファイル編集の注意事項】
# 1. 「:（コロン）」の後ろには、必ず「半角スペース」を1つ入れてください。
#    ○ 正： key: value
#    × 誤： key:value (スペースなし)
# 2. 段落（字下げ）には、必ず「半角スペース」を使ってください。
#    × 絶対に「全角スペース」や「タブ（Tab）」を使わないでください。
# 3. 文言に「#」や「:」を含める場合は、全体を ' ' で囲んでください。
#    例： message: 'エラー番号: #001'
# 4. 保存時の文字コードは「UTF-8」にしてください。
# 5. 文字列を囲うときはシングルクォーテーションで
# ==============================================================================

ルートフォルダ: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化Remake\.ROOT'

ファイルパス:
  PW一覧: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\テスト用ファイル\クライアント別PW一覧.xlsx'
  案件管理シートFMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化Remake\各種FMT\【FMT】案件管理シート.xlsx'
  チェック結果FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】作成済み案件管理シートチェック結果.xlsx'
  送付対象クライアント一覧FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】案件管理シート送付対象クライアント一覧.xlsx'
  受理不備チェック結果FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】案件管理シート受理不備チェック結果.xlsx'
  着工報告ご依頼FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】着工報告ご依頼.xlsx'
  ドキュメント振り分け結果FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】ドキュメント振り分け結果.xlsx'
  案件アラートFMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化Remake\各種FMT\【FMT】案件アラート.xlsx'
  案件アラートチェック結果FMT: 'C:\Users\UU249160\Documents\.SANREMO\自動化\全国化\【FMT】作成済み案件アラートチェック結果.xlsx'

# メモリ消費量抑えるため（小さいと時間かかる、大きいと重くなる）
xw_RESTART_INTERVAL: 20

案件管理シート:
  シート名: "返信用★案件管理シート"
  保護パスワード: "suumo2610!"
  列名:
    - "資料請求日"
    - "予約希望日時"
    - "反響種別"
    - "モデルハウス名"
    - "依頼番号"
    - "名前（漢字）"
    - "名前（かな）"
    - "年齢"
    - "郵便番号"
    - "住所1(都道府県)"
    - "住所2(市区町村以降)"
    - "E-mailアドレス"
    - "電話番号"
    - "建設予定地（名称）"
    - "①最終更新日​"
    - "②ご商談状況​"
    - "③初回来場日​"
    - "④契約予定日​"
    - "営業担当者氏名※任意"
    - "重複※更新先の依頼番号を入力"
    - "メモ※メモの記載内容は次回以降引き継がれません"
    - "お客様来場聞き取り日"
    - "お客様来場時期(ヒアリング経由)"
    - "お客様来場日(来場キャンペーン応募情報経由)"
    - "お客様申告契約日​"

  全体範囲: "B:Z"
  入力範囲: "P:V"
  空列範囲: "V:V"

  商談状況:
    - "資料送付済み"
    - "追客中"
    - "日程調整中"
    - "来場・商談"
    - "土地探し中"
    - "概算プラン見積り"
    - "詳細プラン見積り"
    - "仮契約・設計契約"
    - "契約済み"
    - "他決"
    - "検討停止"
    - "営業停止"
    - "不明"
    - "重複につき更新停止"

不備:
  ファイル形式チェック: "エクセル(xlsx)形式ではありません"
  過去分ファイルチェック: "今月分の案件管理シートではありません"
  CL入力欄削除列チェック: "列が削除されています"
  CL入力欄追加列チェック: "列が1部追加されています"
  依頼番号空白チェック: "依頼番号が未入力の箇所があります"
  商談ステータスチェック: "②商談状況に選択不可の内容があります"
  日付データ型チェック: "日付列に日付形式以外の入力があります"
  重複依頼番号データ型チェック: "⑥重複に数値形式以外の入力があります"
  CL入力欄文字化けチェック: "文字化けしている箇所があります"

案件アラート:
  シート名: "案件アラート"
  全体範囲: "C:W"
